{% set name = "xgrammar" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42bcc5c4187ff9cb6edc44ff5f56030d8b69d62c7576f674a5a074f71b68b1fa

build:
  # Skipping osx builds for now due to troubls building mlx-lm and mlx packages
  # 3.14 support from 0.1.30
  #skip: true # [osx]
  number: 0
  missing_dso_whitelist:
    # libtvm_ffi.so will get loaded by xgrammar code (and apache-tvm-ffi code) before
    # libxgrammar_bindings.so will attempt to load it, so it will already be loaded into
    # the applications memory space before it is needed. There is no guarantee that this
    # will always work. A change in behavior in either xgrammar or apache-tvm-ffi could
    # change this, so the apache-tvm-ffi version must be pinned exactly. This behavior
    # must be verified for every new version of xgrammar.
    # See: https://github.com/mlc-ai/xgrammar/blob/v0.2.2/python/xgrammar/__init__.py#L1
    # and https://github.com/mlc-ai/xgrammar/blob/v0.2.2/python/xgrammar/load_binding.py
    # and https://github.com/apache/tvm-ffi/blob/v0.1.9/python/tvm_ffi/__init__.py#L33-L36
    - "**/libtvm_ffi.so"      # [linux]
    - "**/tvm_ffi.dll"        # [win]
    - "**/libtvm_ffi.dylib"   # [osx]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja-base

  host:
    - python
    - scikit-build-core >=0.10.0
    # apache-tvm-ffi must be pinned exactly. See missing_dso_whitelist comment for more details.
    - apache-tvm-ffi ==0.1.9
    - pip
  run:
    - python
    # apache-tvm-ffi must be pinned exactly. See missing_dso_whitelist comment for more details.
    - apache-tvm-ffi ==0.1.9
    - pydantic
    - pytorch >=1.10.0
    - transformers >=4.38.0
    - triton # [linux and x86_64]
    - numpy
    - typing-extensions >=4.9.0

    # Skipping osx builds for now due to troubls building mlx-lm and mlx packages
    - mlx-lm # [osx and arm64]

test:
  source_files:
    - tests/
  imports:
    - xgrammar
  commands:
    - pip check
    - pytest -m "not hf_token_required"
  requires:
    - pip
    - protobuf
    - pytest
    - huggingface_hub
    - sentencepiece
    - tiktoken
    - transformers<4.50.0 # [osx]

about:
  home: https://github.com/mlc-ai/xgrammar
  summary: XGrammar is an open-source library for efficient, flexible, and portable structured generation.
  description: |
    XGrammar is an open-source library for efficient, flexible, and portable
    structured generation. It leverages constrained decoding to ensure 100%
    structural correctness of the output. It supports general context-free
    grammar to enable a broad range of structures, including JSON, regex,
    custom context-free grammar, etc.
  # xgrammar uses the Apache license, but it vendors picojson, which appears to use a
  # combination of the Apache 2 and BSD-2-Clause licenses.
  license: Apache-2.0 AND BSD-2-Clause
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  dev_url: https://github.com/mlc-ai/xgrammar
  doc_url: https://github.com/mlc-ai/xgrammar

extra:
  recipe-maintainers:
    - zbowling
    - Ubospica
